// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUhCscPJXRGkymZccwblOHP5DujFeuioM',
    appId: '1:695581194330:web:dbd6a7d6ea48a8613b8063',
    messagingSenderId: '695581194330',
    projectId: 'spendsync-b3ac4',
    authDomain: 'spendsync-b3ac4.firebaseapp.com',
    storageBucket: 'spendsync-b3ac4.firebasestorage.app',
    measurementId: 'G-ZQDYH98S7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRDX2iXcugPD-8BzeLVmDGFpRUj0ADleo',
    appId: '1:695581194330:android:1a60f79ff7140c793b8063',
    messagingSenderId: '695581194330',
    projectId: 'spendsync-b3ac4',
    storageBucket: 'spendsync-b3ac4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAfQf_X5yew0-qDY5F-kK1NzEceC6Gdhw',
    appId: '1:695581194330:ios:babda46cdda472063b8063',
    messagingSenderId: '695581194330',
    projectId: 'spendsync-b3ac4',
    storageBucket: 'spendsync-b3ac4.firebasestorage.app',
    iosClientId: '695581194330-csnds8vjhknr6ldgai6889j7s45o2r3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendapp',
  );

}